Write git sha to a profile.d script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,3 +1,23 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-exit 0
+# fail fast
+set -e
+
+BUILD_DIR="$1"
+CACHE_DIR="$2"
+ENV_DIR="$3"
+PROFILE_PATH="$BUILD_DIR/.profile.d/git-sha.sh"
+
+create_env() {
+  # populate profile.d
+  mkdir -p $(dirname $PROFILE_PATH)
+}
+
+write_profile() {
+  echo "=====> Writing SOURCE_VERSION ($SOURCE_VERSION) to $DEST"
+  echo "GIT_SHA=\"$SOURCE_VERSION\"" >> $PROFILE_PATH
+}
+
+create_env
+write_profile
